### PR TITLE
Fix phone number format on user profile edit

### LINKED ISSUE #369: The phone number input on the manager's profile edit page should be have +98.

### PR DESCRIPTION
**Pull request by Arshiya-rze**

### CODE REVIEW

File: client/src/app/components/user/user-profile/user-profile.component.ts [hunk 1]
```diff
@@ -340,11 +352,17 @@ export class UserProfileComponent implements OnInit {
           ? rawGender
           : null;
 
+      const rawPhone = this.profile.phoneNum ?? '';
+      const phoneForInput =
+        rawPhone.startsWith('98') && rawPhone.length === 12
+          ? rawPhone.substring(2)
+          : rawPhone;
+
       this.profileFg.patchValue({
```
Comment (FaranakBaran) [inline client/src/app/components/user/user-profile/user-profile.component.ts:352]: email & userName byd pak beshan chon dar FormGroup delete shodan

Comment (Arshiya-rze) [reply client/src/app/components/user/user-profile/user-profile.component.ts:352]: Done

**Review by FaranakBaran — APPROVED** [review]
Done
