### PR TITLE
Fix profile photo upload and return photo in user profile

### LINKED ISSUE #243: Upload profile photo for manager

### PR DESCRIPTION
**Pull request by Arshiya-rze**
- Added Photo to ProfileDto and mapped AppUser.Photo in mapper
- Updated AppUser to store MemberPhoto correctly
- Improved get-profile response to return url_256 for avatar
- Updated frontend to read photo from API and persist after refresh
- Final result: profile photo upload works correctly and stays visible after reload

### CODE REVIEW

File: client/src/app/components/user/user-profile/user-profile.component.ts [hunk 1]
```diff
@@ -130,9 +131,23 @@ export class UserProfileComponent implements OnInit {
             dobMoment = moment(`${approxYear}-01-01`, 'YYYY-MM-DD');
           }
 
+          const anyData = data as any;
+
+          let photoUrl: string | undefined =
+            anyData.photoUrl ??
```
Comment (FaranakBaran) [inline client/src/app/components/user/user-profile/user-profile.component.ts:137]: Dar in ghesmat byd url_165 ro ham check koni ke backend har modeli bargardond, als dorost set beshe

**Review by FaranakBaran — COMMENTED** [review]
Image

File: client/src/app/components/user/user-profile/user-profile.component.ts (hunk 1 above)
Comment (Arshiya-rze) [reply client/src/app/components/user/user-profile/user-profile.component.ts:137]: Done

**Review by FaranakBaran — APPROVED** [review]
Done
